api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        jsonhal: [ 'application/hal+json' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
#    exception_to_status:
#        App\Exception\EmailAlreadyUsedException: 422
#        App\Exception\ValidateErrorException: 422
#        App\Exception\NotFoundItemException: 404
#        App\Exception\UserNotFoundException: 404