twig:
    file_name_pattern: '*.twig'
    debug: true
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': Twig

when@test:
    twig:
        strict_variables: true
